version: "3"


services:
  postgres_test_db:
    container_name: test_db
    image: postgres:alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=testdb